

class CustomException(Exception):

    def __init__(self, *args, **kwargs):
        pass
